services:
  - type: web
    name: hexalegends-bot
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:5000 --timeout 120
    envVars:
      - key: BOT_TOKEN
        value: "8228108336:AAF3OWn5-nYQjEZhNactyldXV9FW9kTtq9k"
